--------------------------------------------------------
--  File created - Sunday-October-18-2020   
--------------------------------------------------------
@C:\Users\QhairunnisaSyed\Desktop\Syed\SEQUENCES\DEPARTMENTS_SEQ.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\SEQUENCES\EMPLOYEES_SEQ.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\SEQUENCES\LOCATIONS_SEQ.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TABLES\COUNTRIES.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TABLES\DEPARTMENTS.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TABLES\EMPLOYEES.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TABLES\JOBS.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TABLES\JOB_HISTORY.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TABLES\LOCATIONS.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TABLES\REGIONS.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TABLES\XX_EMP.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\VIEWS\EMP_DETAILS_VIEW.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\COUNTRY_C_ID_PK.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\DEPT_ID_PK.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\DEPT_LOCATION_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_DEPARTMENT_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_EMAIL_UK.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_EMP_ID_PK.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_JOB_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_MANAGER_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_NAME_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JHIST_DEPARTMENT_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JHIST_EMPLOYEE_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JHIST_EMP_ID_ST_DATE_PK.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JHIST_JOB_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JOB_ID_PK.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\LOC_CITY_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\LOC_COUNTRY_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\LOC_ID_PK.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\LOC_STATE_PROVINCE_IX.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\REG_ID_PK.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\COUNTRY_C_ID_PK_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\DEPT_ID_PK_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\DEPT_LOCATION_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_EMAIL_UK_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_EMP_ID_PK_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_DEPARTMENT_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_JOB_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_MANAGER_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\EMP_NAME_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JOB_ID_PK_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JHIST_EMP_ID_ST_DATE_PK_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JHIST_JOB_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JHIST_EMPLOYEE_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\JHIST_DEPARTMENT_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\LOC_ID_PK_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\LOC_CITY_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\LOC_STATE_PROVINCE_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\LOC_COUNTRY_IX_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\INDEXES\REG_ID_PK_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TRIGGERS\SECURE_EMPLOYEES.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TRIGGERS\UPDATE_JOB_HISTORY.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TRIGGERS\SECURE_EMPLOYEES_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\TRIGGERS\UPDATE_JOB_HISTORY_1.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\PROCEDURES\ADD_JOB_HISTORY.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\PROCEDURES\SECURE_DML.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\CONSTRAINTS\COUNTRIES.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\CONSTRAINTS\DEPARTMENTS.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\CONSTRAINTS\EMPLOYEES.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\CONSTRAINTS\JOBS.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\CONSTRAINTS\JOB_HISTORY.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\CONSTRAINTS\LOCATIONS.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\CONSTRAINTS\REGIONS.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\REF_CONSTRAINTS\COUNTRIES.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\REF_CONSTRAINTS\DEPARTMENTS.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\REF_CONSTRAINTS\EMPLOYEES.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\REF_CONSTRAINTS\JOB_HISTORY.sql
@C:\Users\QhairunnisaSyed\Desktop\Syed\REF_CONSTRAINTS\LOCATIONS.sql
